import type { Metadata } from "next";
import { Geist, Fredericka_the_Great, Rubik, Ubuntu_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fredericka = Fredericka_the_Great({
  variable: "--font-fredericka",
  weight: "400",
  subsets: ["latin"],
});

const rubik = Rubik({
  weight: "400",
  variable: "--font-rubik",
  subsets: ["latin"],
});

const ubuntu = Ubuntu_Mono({
  weight: "400",
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nafis Codes Away",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${ubuntu.className} light`}>
      <body className="bg-white">
        <header>
         <nav>
           <Navbar/> 
         </nav> 
        </header>

          {children}
        
        <footer className="flex flex-wrap items-center justify-center">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
